# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-21 18:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scores', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sessioninstance',
            name='session',
        ),
        migrations.DeleteModel(
            name='SessionInstance',
        ),
    ]
